parameters:
  - name: IMAGE_NAME
    value: dagster
  - name: IMAGE_TAG
    value: core

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${IMAGE_NAME}-build
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      name: ${IMAGE_NAME}
    spec:
      lookupPolicy:
      local: true
    labels:
      name: ${IMAGE_NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${IMAGE_NAME}-build-config
      labels:
        component: "${IMAGE_NAME}"
    spec:
      source:
        binary: {}
      strategy:
        dockerStrategy:
          dockerfilePath: build-support/Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: "${IMAGE_NAME}:${IMAGE_TAG}"
        noCache: false
      runPolicy: Serial # Queue builds to disable concurrent build
      